### ISSUE TITLE
Provide readme to configure the debugger for Camel

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-dap-client-vim#1]
based on https://microsoft.github.io/debug-adapter-protocol/implementors/tools/ , there are 2 extensions possible:
* https://github.com/puremourning/vimspector
* https://github.com/mfussenegger/nvim-dap

Vim inspector sounds more advanced; i think we should go with this one.

**Comment by Navyashree0923** [comment]
Provided readme to configure the debugger for Camel #2
